#!/bin/bash

WADKA_VERSION="0.2.3-dev"
WADKA_RELEASE_DATE="Jan 12, 2018"
WADKA_EXECUTABLE_COMMANDS=("doc" "help" "up" "build" "version")
SUPPORTED_PLATFORMS=("woocommerce" "magento" "eccube")
REPOSITORY_ACCOUNT="https://github.com/guzzilar"
VERSIONING_LOCATION=".version"

app_name=""
build_location=""
build_platform=""
build_source=""
build_version="latest"
container_base_location="containers"
container_location=""

the_command=""
arg_position=0

###
 # Wadka's document
 ##
help () {
    doc
}

doc () {
    echo -e "
    Wadka Document:
    ---------------------
    usage: wadka <command> <platform>[:<version>] [<app_name>]

    Available commands
    \tdoc, help\tDisplay the Wadka's document

    \tup\t\tBoot up a target container

    \tbuild\t\tRe-build a target container before boot up

    \tversion\t\tShow Wadka's current version.


    SUPPORTED PLATFORMS
    ---------------------
    eccube, magento, woocommerce


    EXAMPLES
    ---------------------
    \t1) ./bin/wadka up woocommerce:3.1.0
    \t2) ./bin/wadka up woocommerce:3.1.0 mywc
    \t3) ./bin/wadka up magento my-magento
    "
}

###
 # Wadka's version
 ##
version () {
    echo -e ".."
    echo -e "Wadka v$WADKA_VERSION (released on  $WADKA_RELEASE_DATE)"
}

###
 # Check if Wadka supports a build target platform.
 #
 # @param $1 string  name of a platform you want to check
 ##
isExecutable () {
    local the_command

    for the_command in ${WADKA_EXECUTABLE_COMMANDS[@]}; do
        [[ $the_command == $1 ]] && {
            return 0
        }
    done

    return 1
}

###
 # Check if Wadka supports a build target platform.
 #
 # @param $1 string  name of a platform you want to check
 ##
isSupportPlatform () {
    local platform

    for platform in ${SUPPORTED_PLATFORMS[@]}; do
        [[ $platform == $1 ]] && {
            return 0
        }
    done

    return 1
}

###
 # Container version checking
 ##
fetchContainer () {
    local container_version=$(curl -s https://api.github.com/repos/guzzilar/docker-$build_platform/git/refs/heads/master | jq '.object.sha' | sed -e 's/^"//' -e 's/"$//')
    container_location=$container_base_location/$build_platform

    echo "Wadka: checking the container version.."

    # Check for container versioning directory.
    if [ ! -d $container_base_location/.versions ]; then
        mkdir -p $container_base_location/.versions
        echo " > Created a $container_base_location/.versions directory."
    fi

    # Cache a versioning file.
    if [ ! -f "$container_base_location/.versions/docker-$build_platform.$container_version" ]; then
        echo " > Found a new version of docker-$build_platform (commit: $container_version)"

        rm -f $container_base_location/.versions/docker-$build_platform.*
        rm -R $container_location

        touch $container_base_location/.versions/docker-$build_platform.$container_version

        echo " > Cached \"$container_base_location/.versions/docker-$build_platform.$container_version\""
    else
        echo " > The container is up-to-date."
    fi

    # Check for base container directory.
    if [ ! -d $container_location ]; then
        mkdir -p $container_location
        echo " > Created a $container_location directory."

        downloadContainer
    fi
}

###
 # Download a container from https://github.com/guzzilar/*
 ##
downloadContainer () {
    local package_location="$REPOSITORY_ACCOUNT/docker-$build_platform/archive/master.zip"
    local tmp_location=$container_location/tmp

    mkdir $tmp_location
    echo "Wadka: download a Docker container from $package_location."
    echo " > Downloading"
    wget -O $tmp_location/docker-$build_platform.zip $package_location

    # 2. Unzip
    echo " > unzip $tmp_location/docker-$build_platform.zip"
    unzip $tmp_location/docker-$build_platform.zip -d $tmp_location/
    echo " > moving file to $container_location."
    mv $tmp_location/docker-$build_platform-master/* $container_location

    # 3. Delete tmp.
    echo " > remove temp files."
    rm -R $tmp_location
}

###
 # Preparation
 ##
initialize () {
    fetchContainer

    build_location="app/$([[ ! -z $app_name ]] && echo $app_name || echo $build_platform)"

    echo ".."
    echo "."
    echo "Wadka: preparing docker..."

    if [ ! -d $build_location ]; then
        mkdir -p $build_location
        echo " > Created a $build_location directory."
    else
        echo " > Cannot create a new app, $build_location already exists."
    fi
}

##
# Boot up a container!
#
up() {
    echo ".."
    echo "Wadka: running up \"$build_platform\" version \"$build_version\" container.."

    initialize

    echo "Wadka: Booting up the docker!"
    echo "Wadka: ================================================================================"

    $container_location/bin/docky-servant up $build_version $build_location
}

##
# Build it!
#
build() {
    echo ".."
    echo "Wadka: running up \"$build_platform\" version \"$build_version\" container.."

    initialize

    echo "Wadka: Booting up the docker!"
    echo "Wadka: ================================================================================"

    $container_location/bin/docky-servant build $build_version $build_location
}

# ..
#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-
# EXECUTION AREA
#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-
# ..
the_command=$1
if ! isExecutable $the_command; then
    echo ".."
    echo "Wadka: command not found, cannot execute the command \"$the_command\"."
    echo ""
    doc
    exit
fi

# Remove "execute command" from arguments.
shift

# Reading arguments.
while [[ $# -gt 0 ]]; do
    case "$1" in
        --source=*)
            build_source="${1#*=}"
            shift
            ;;

        *)
            [[ -z $build_platform ]] && {
                OIFS=$IFS
                IFS=":"
                target=($1)

                if ! isSupportPlatform ${target[0]}; then
                    echo ".."
                    echo "Wadka: error, platform \"$1\" did not match with any platform(s) I supported."
                    exit
                fi

                build_platform=${target[0]}
                build_version=$([[ ! -z ${target[1]} ]] && echo ${target[1]} || echo "latest")

                IFS=$OIFS
                arg_position=1

                shift
                continue
            }

            [[ $arg_position -eq 1 ]] && {
                app_name=$1

                shift
                continue
            }
            ;;
    esac
done

$the_command

# [[ ! -z $build_platform ]] && {
    # $execute_command
# }
